_wandb:
    value:
        cli_version: 0.19.4
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.11.11
            "5": 0.19.4
            "8":
                - 5
            "12": 0.19.4
            "13": linux-x86_64
batch_size:
    value: 32
epochs:
    value: 5
lr:
    value: 0.001
