workerPoolSpecs:
  - machineSpec:
      machineType: n1-highmem-2
    replicaCount: 1
    containerSpec:
      imageUri: "europe-west1-docker.pkg.dev/animal-classification-555/animal-classification/train-image@sha256:a1a7a5c02b692a24f77cddd95e28abc934d70b331213fd7e4bb618bde5b52792"
      command: ["python", "src/animal_classification/train.py", "--sweep"]
      env:
        - name: WANDB_API_KEY
          value: "6ef13821cd6974d79eeb91a1119285e45597a314"
