workerPoolSpecs:
  machineSpec:
    machineType: n1-highmem-8
  replicaCount: 1
  containerSpec:
    imageUri: "europe-west1-docker.pkg.dev/animal-classification-555/animal-classification/evaluate-image:latest"
    command: ['python', 'src/animal_classification/train.py']
    args: ['--epochs=10', '--batch-size=128']
